CREATE  table Students(
	reg_no INT,
	first_name VARCHAR (255),
	last_name VARCHAR (255),
	Course VARCHAR (255),
	Gender VARCHAR(255),
	D_F_B DATE
	
	
INSERT  INTO Students(reg_no,first_name,last_name,Course,Gender,D_F_B),
VALUES(1/2016,"john","mutuku","DCS", "male", "1"3/16/1990"),
	(2/2016,"steve", "kipkorir", "DCS","male", "13/3/1985"),
	(3/2016, "susan", "mutua", "CIT", "female", "19/11/1986"),
	(4/2017, "steve", "kingori", "DBIT","male", "1/3/1978")
;
	
	
	SELECT * FROM student;
	